[package]
org = "dilhashanazeer"
name = "InventoryService"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="microrts"
name="static_analyzer"
version="1.0.0"
repository="local"