name: Build and Push Docker images to GCR

on:
  push:
    branches:
      - simple-microservices

env:
  PROJECT_ID: microrts-sample
  CART_SERVICE_IMAGE: cartservice
  INVENTORY_SERVICE_IMAGE: inventoryservice
  PAYMENT_SERVICE_IMAGE: paymentservice
  ORDER_SERVICE_IMAGE: orderservice
  PRODUCT_SERVICE_IMAGE: productservice
  SHIPPING_SERVICE_IMAGE: shippingservice
  USER_SERVICE_IMAGE: userservice
  TAG: 1.0.0

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}
      ## cart service
      - name: Build hipstershop/cartservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          files: cartservice.build.dockerfile
          tags: hipstershop/cartservice-build

      - name: Build and Push Cartservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          files: cartservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.CART_SERVICE_IMAGE }}:${{ env.TAG }}

      ## inventory service
      - name: Build hipstershop/inventoryservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          file: inventoryservice.build.dockerfile
          tags: hipstershop/inventoryservice-build

      - name: Build and Push inventoryservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: inventoryservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.INVENTORY_SERVICE_IMAGE }}:${{ env.TAG }}
