name: Build and Push Docker images to GCR

on:
  push:
    branches:
      - simple-microservices

env:
  PROJECT_ID: microrts-sample
  CART_SERVICE_IMAGE: cartservice
  CART_SERVICE_BUILD_IMAGE: build-cartservice
  INVENTORY_SERVICE_BUILD_IMAGE: build-inventoryservice
  INVENTORY_SERVICE_IMAGE: inventoryservice
  PAYMENT_SERVICE_BUILD_IMAGE: build-paymentservice
  PAYMENT_SERVICE_IMAGE: paymentservice
  ORDER_SERVICE_BUILD_IMAGE: build-orderservice
  ORDER_SERVICE_IMAGE: orderservice
  PRODUCT_SERVICE_BUILD_IMAGE: build-productservice
  PRODUCT_SERVICE_IMAGE: productservice
  SHIPPING_SERVICE_BUILD_IMAGE: build-shippingservice
  SHIPPING_SERVICE_BUILD_IMAGE: build-shippingservice
  SHIPPING_SERVICE_IMAGE: shippingservice
  USER_SERVICE_BUILD_IMAGE: build-userservice
  USER_SERVICE_IMAGE: userservice
  TAG: 1.0.0

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}

      ## cart service
      - name: Build cartservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: cartservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.CART_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push Cartservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: cartservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.CART_SERVICE_IMAGE }}:${{ env.TAG }}

      ## inventory service
      - name: Build inventoryservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: inventoryservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.INVENTORY_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push inventoryservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: inventoryservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.INVENTORY_SERVICE_IMAGE }}:${{ env.TAG }}
    
      ## order service
      - name: Build orderservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: orderservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.ORDER_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push orderservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: orderservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.ORDER_SERVICE_IMAGE }}:${{ env.TAG }}

      ## payment service
      - name: Build paymentservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: paymentservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.PAYMENT_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push paymentservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: paymentservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.PAYMENT_SERVICE_IMAGE }}:${{ env.TAG }}

      ## product service
      - name: Build productservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: productservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.PRODUCT_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push productservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: productservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.PRODUCT_SERVICE_IMAGE }}:${{ env.TAG }}

      ## shipping service
      - name: Build shippingservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: shippingservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.SHIPPING_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push shippingservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: shippingservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.SHIPPING_SERVICE_IMAGE }}:${{ env.TAG }}

      ## user service
      - name: Build userservice-build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: userservice.build.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.USER_SERVICE_BUILD_IMAGE }}:${{ env.TAG }}

      - name: Build and Push userservice Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: userservice.dockerfile
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.USER_SERVICE_IMAGE }}:${{ env.TAG }}